=== RWTH-HPC/static-filter-rma-c3po24/MUST/externals/GTI/system-builder/dtd/layout-specification.dtd
<!--
  This file is part of GTI (Generic Tool Infrastructure)

  Copyright (C)
    2008-2019 ZIH, Technische Universitaet Dresden, Federal Republic of Germany
    2008-2019 Lawrence Livermore National Laboratories, United States of America
    2013-2019 RWTH Aachen University, Federal Republic of Germany

  See the LICENSE file in the package base directory for details
-->

<!-- Root node of the layout specification.
-->
<!ELEMENT layout-specification (levels, communications)>

<!-- Node for all level nodes.
-->
<!ELEMENT levels (level)*>

<!-- Node for a level.
  order: Number 0-N, 0 is application level, 1 is level above that and so on
  place-name: Name of the GTI place to use for this level, for order 0 its always application
  size: Absolute level size (#of processes)
-->
<!ELEMENT level (analyses)>
<!ATTLIST level
   order CDATA #REQUIRED
   place-name CDATA #REQUIRED
   size CDATA #REQUIRED
>

<!-- Node for all analyses of a level.
-->
<!ELEMENT analyses (analysis)*>

<!-- Node for an analysis.
     name: name of the analysis
     group: group name of the analysis group it belongs to
-->
<!ELEMENT analysis EMPTY>
<!ATTLIST analysis
   name CDATA #REQUIRED
   group CDATA #REQUIRED
>

<!-- Node for inter level communication specification.
-->
<!ELEMENT communications (default, (connection)*)>

<!-- Node for the default communication mode.
       (Default mode for inter layer communication)
-->
<!ELEMENT default (comm-strategy, comm-protocol)>

<!-- A connection between two levels.
     If the levels differ it is a inter communication between layers,
     for equal levels it is an intra communication.
     Either it specifies a comm strategy and a 
     comm protocol, or it uses the default 
     communication mechanism (only for inter communication).
     Intra communication is not allowed on the application level!
  - bottom-level: order of the level that
                  sends information about records.
  - top-level: order of the level that receives 
               information about records.
  - distribution: Either "uniform" or "by-block". Specifies how nodes in the lower
               level are distributed across the upper level. For uniform, each node
               in the upper level is mapped to an equal number of lower level ranks.
               If an exact distribution is not possible, remaining nodes are added to 
               the first nodes of the upper layer. E.g., distributiong nodes L0-L6 to three 
               nodes on the upper layer (U0-U2) results in L0,L1,L2 connected to U0; L3,L4 
               connected to U1; and L5, L6 connected to U2 with the uniform distribution.
               The "by-block" distribution uses a specified blocksize (blocksize attribute must 
               be set). In this case each complete block of the lower level is connected with 
               one node of the upper level. The last block may not be used completely.
               E.g., distributiong nodes L0-L6 to three 
               nodes on the upper layer (U0-U2) with a blocksize of 3 results in L0,L1,L2 
               connected to U0; L3,L4,L5 connected to U1; and L6 connected to U2 with 
               the by-block distribution. [optional, default uniform]
  - blocksize: Specifies distribution for distribution="by-block" [optional, must be set if
                     by-block is used].
-->
<!ELEMENT connection (comm-strategy?, comm-protocol?)>
<!ATTLIST connection
   bottom-level CDATA #REQUIRED
   top-level CDATA #REQUIRED
   distribution CDATA #IMPLIED
   blocksize CDATA #IMPLIED
>

<!-- Node for a communication strategy.
  - name: name of the strategy (module name of the comm up module
                for inter communication)
-->
<!ELEMENT comm-strategy (settings)>
<!ATTLIST comm-strategy
   name CDATA #REQUIRED
>

<!-- Node for a communication protocol.
  - name: name of the protocol
-->
<!ELEMENT comm-protocol (settings)>
<!ATTLIST comm-protocol
   name CDATA #REQUIRED
>

<!-- Settings for a strategy or protocol.
     Only needed for settings that do not
     use its default value.
-->
<!ELEMENT settings (setting)*>

<!-- Node for a setting.
     name: name of the setting
     value: value for the setting
-->
<!ELEMENT setting EMPTY>
<!ATTLIST setting
   name CDATA #REQUIRED
   value CDATA #REQUIRED
>

=== RWTH-HPC/static-filter-rma-c3po24/MUST/externals/GTI/tests/HelloWeaver/layout-spec.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  This file is part of GTI (Generic Tool Infrastructure)

  Copyright (C)
    2008-2019 ZIH, Technische Universitaet Dresden, Federal Republic of Germany
    2008-2019 Lawrence Livermore National Laboratories, United States of America
    2013-2019 RWTH Aachen University, Federal Republic of Germany

  See the LICENSE file in the package base directory for details
-->

<!DOCTYPE layout-specification SYSTEM "/Users/hilbrich/workspace/must/system-builder/dtd/layout-specification.dtd">
<layout-specification>
	<levels>
		<level order="0" size="2" place-name="mpi_app">
        <analyses></analyses>
		</level>
        <level order="1" size="1" place-name="mpi_place">
        <analyses>
            <analysis name="PrintSendRecv" group="HelloWeaver" />
        </analyses>
        </level>
    </levels>
	<communications>
        <default>
            <comm-strategy name="CStratSimpleUp"><settings></settings></comm-strategy>
            <comm-protocol name="CProtMpiSplited"><settings></settings></comm-protocol>
        </default>
        <connection top-level="1" bottom-level="0"></connection>
    </communications>
</layout-specification>

=== RWTH-HPC/static-filter-rma-c3po24/MUST/externals/GTI/tests/simple-case-layout-specification2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  This file is part of GTI (Generic Tool Infrastructure)

  Copyright (C)
    2008-2019 ZIH, Technische Universitaet Dresden, Federal Republic of Germany
    2008-2019 Lawrence Livermore National Laboratories, United States of America
    2013-2019 RWTH Aachen University, Federal Republic of Germany

  See the LICENSE file in the package base directory for details
-->

<!DOCTYPE layout-specification SYSTEM "/Users/hilbrich/workspace/must/system-builder/dtd/layout-specification.dtd">
<layout-specification>
	
	<levels>
		<level order="0" size="30" place-name="mpi_app">
			<analyses>
				<analysis name="checkArray" group="simple" /></analyses>
		</level>
		<level order="1" size="9" place-name="mpi_place">
			<analyses>
				<analysis name="handleSizes" group="simple" ></analysis>
				</analyses>
		</level>
		<level order="3" size="1" place-name="mpi_place">
			<analyses>
			     <analysis name="printFloatSum" group="simple" />
			</analyses>
		</level>
		<level order="2" size="4" place-name="mpi_place">
			<analyses></analyses>
		</level></levels>
	<communications>
		<default><comm-strategy name="CStratSimpleUp"><settings></settings></comm-strategy><comm-protocol name="CProtMpiSplited"><settings></settings></comm-protocol></default>
		<connection top-level="1" bottom-level="0"></connection>
		<connection top-level="2" bottom-level="1"></connection>
		<connection top-level="3" bottom-level="2"></connection></communications></layout-specification>

=== RWTH-HPC/static-filter-rma-c3po24/MUST/tests/Mustrun/layout.xml
<?xml version="1.0"?>

<!--
  Part of the MUST Project, under BSD-3-Clause License
 See https://hpc.rwth-aachen.de/must/LICENSE for license information.
  SPDX-License-Identifier: BSD-3-Clause
-->

<!DOCTYPE layout-specification SYSTEM "@MUST_SPECIFICATION_DTD_PATH@/layout-specification.dtd">
<layout-specification>
    <levels>
        <level order="0" size="4" place-name="mpi_app">
            <analyses>
                <analysis name="DatatypePredefs" group="MUST_Resource"/>
                <analysis name="CommPredefs" group="MUST_Resource"/>
                <analysis name="FinalizeNotify" group="MUST_Base"/>
                <analysis name="DCollectiveInitNotify" group="MUST_DistributedDeadlock"/>

                <analysis name="FinalizeNotify" group="MUST_Base"></analysis>
            </analyses>
        </level>
        <level order="1" size="2" place-name="mpi_place">
            <analyses>

            </analyses>
        </level>
        <level order="2" size="1" place-name="mpi_place">
            <analyses>

                <analysis name="MsgLoggerStdOut" group="MUST_Base"></analysis>
                <analysis name="MsgLoggerHtml" group="MUST_Base"></analysis>
            </analyses>
        </level>
    </levels>
    <communications>
        <default>
            <comm-strategy name="CStratSimpleUp">
                <settings></settings>
            </comm-strategy>
            <comm-protocol name="CProtMpiSplited">
                <settings></settings>
            </comm-protocol>
        </default>
        <connection top-level="1" bottom-level="0"></connection>
        <connection top-level="2" bottom-level="1"></connection>
    </communications>
</layout-specification>

=== RWTH-HPC/static-filter-rma-c3po24/MUST/tests/Mustrun/layout-hybrid.xml
<?xml version="1.0"?>

<!--
  Part of the MUST Project, under BSD-3-Clause License
 See https://hpc.rwth-aachen.de/must/LICENSE for license information.
  SPDX-License-Identifier: BSD-3-Clause
-->

<!DOCTYPE layout-specification SYSTEM "@MUST_SPECIFICATION_DTD_PATH@/layout-specification.dtd">
<layout-specification>
    <levels>
        <level order="0" size="32" place-name="thread_app">
            <analyses>
            </analyses>
        </level>
        <level order="1" size="8" place-name="thread_place">
            <analyses>
            </analyses>
        </level>
        <level order="2" size="4" place-name="mpi_place">
            <analyses>
            </analyses>
        </level>
        <level order="3" size="1" place-name="mpi_place">
            <analyses>
            </analyses>
        </level>
    </levels>
    <communications>
        <default>
            <comm-strategy name="CStratSimpleUp">
                <settings></settings>
            </comm-strategy>
            <comm-protocol name="CProtMpiSplited">
                <settings></settings>
            </comm-protocol>
        </default>
        <connection top-level="1" bottom-level="0"></connection>
        <connection top-level="2" bottom-level="1"></connection>
        <connection top-level="3" bottom-level="2"></connection>
    </communications>
</layout-specification>

=== RWTH-HPC/static-filter-rma-c3po24/MUST/cmakemodules/layout.template.xml
<?xml version="1.0"?>

<!--
  Part of the MUST Project, under BSD-3-Clause License
 See https://hpc.rwth-aachen.de/must/LICENSE for license information.
  SPDX-License-Identifier: BSD-3-Clause
-->

<!DOCTYPE layout-specification SYSTEM "@MUST_SPECIFICATION_DTD_PATH@/layout-specification.dtd">
<layout-specification>
	<levels>
		<level order="0" size="${numProcsL0}" place-name="mpi_app">
			<analyses>
			    <analysis name="DatatypePredefs" group="MUST_Resource"/>
			    <analysis name="CommPredefs" group="MUST_Resource"/>
			    <analysis name="FinalizeNotify" group="MUST_Base"/>
			    <analysis name="DCollectiveInitNotify" group="MUST_DistributedDeadlock"/>
				${level0ModString}
			</analyses>
		</level>
		<level order="1" size="${numProcsL1}" place-name="mpi_place">
			<analyses>
				${level1ModString}
			</analyses>
		</level>
		<level order="2" size="1" place-name="mpi_place">
			<analyses>
				${level2ModString}	
			</analyses>
		</level></levels>
	<communications>
		<default>
			<comm-strategy name="CStratSimpleUp">
				<settings></settings>
			</comm-strategy>
			<comm-protocol name="CProtMpiSplited">
				<settings></settings>
			</comm-protocol>
		</default>
		<connection top-level="1" bottom-level="0"></connection>
		<connection top-level="2" bottom-level="1"></connection>
	</communications>
</layout-specification>

=== RWTH-HPC/static-filter-rma-c3po24/MUST/externals/GTI/tests/example-layout-specification.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  This file is part of GTI (Generic Tool Infrastructure)

  Copyright (C)
    2008-2019 ZIH, Technische Universitaet Dresden, Federal Republic of Germany
    2008-2019 Lawrence Livermore National Laboratories, United States of America
    2013-2019 RWTH Aachen University, Federal Republic of Germany

  See the LICENSE file in the package base directory for details
-->

<!DOCTYPE layout-specification SYSTEM "/home/hilbrich/workspace/must/system-builder/dtd/layout-specification.dtd">
<layout-specification>
	
	<levels><level order="0" place-name="mpi_app" size="4"><analyses></analyses>
		</level>
		<level order="1" size="2" place-name="mpi_place">
			<analyses>
				<analysis name="checkRequests" group="MPI-Check" /></analyses>
		</level>
		<level order="2" size="1" place-name="mpi_place">
			<analyses>
				<analysis name="check_array_something" group="MPI-Check" /></analyses>
		</level>
		<level order="3" size="1" place-name="mpi_place">
			<analyses>
				<analysis name="test" group="MPI-Check" /></analyses>
		</level></levels>
	<communications>
		<default><comm-strategy name="CStratSimpleUp"><settings>
				</settings></comm-strategy><comm-protocol name="CProtMpiSplited"><settings>
				</settings></comm-protocol></default>
		<connection bottom-level="0" top-level="1"></connection>
		<connection top-level="2" bottom-level="1">
			<comm-strategy name="CStratSimpleUp">
				<settings>
				</settings>
			</comm-strategy>
			<comm-protocol name="CProtMpiSplited">
				<settings>
				</settings>
			</comm-protocol></connection>
		<connection top-level="2" bottom-level="0"></connection>
		<connection top-level="3" bottom-level="0"></connection></communications></layout-specification>

=== RWTH-HPC/static-filter-rma-c3po24/MUST/tests/VectorClock/layout.template.xml
<?xml version="1.0"?>

<!--
  Part of the MUST Project, under BSD-3-Clause License
 See https://hpc.rwth-aachen.de/must/LICENSE for license information.
  SPDX-License-Identifier: BSD-3-Clause
-->

<!DOCTYPE layout-specification SYSTEM "@MUST_SPECIFICATION_DTD_PATH@/layout-specification.dtd">
<layout-specification>
	<levels>
		<level order="0" size="${totalProcs}" place-name="mpi_app">
			<analyses>
                <!--<analysis name="DCollectiveInitNotify" group="MUST_DistributedDeadlock"/>-->
			    <analysis name="DatatypePredefs" group="MUST_Resource"/>
			    <analysis name="CommPredefs" group="MUST_Resource"/>
                <!--
				<analysis name="PControl" group="GTI_IMPLICIT"/>
			    <analysis name="ProfilerMpi" group="GTI_IMPLICIT"/>
                -->
                <!--<analysis name="FinalizeNotify" group="MUST_Base"/>-->
				${level0ModString}
			</analyses>
		</level>
		<level order="1" size="${numPlaces}" place-name="mpi_place">
			<analyses>
                <analysis name="VectorClock" group="GTI_IMPLICIT"/>
                <analysis name="VectorClockWrapper" group="MUST_VectorClock"/>
                <!--
			    <analysis name="ProfilerMpi" group="GTI_IMPLICIT"/>
                -->
				${level1ModString}
			</analyses>
		</level>
    </levels>
	<communications>
		<default>
			<comm-strategy name="CStratSimpleUp">
				<settings></settings>
			</comm-strategy>
			<comm-protocol name="CProtMpiSplited">
				<settings></settings>
			</comm-protocol>
		</default>
		<connection top-level="1" bottom-level="0"></connection>
		<connection top-level="1" bottom-level="1">
			<comm-strategy name="CStratPRecvIntra">
				<settings></settings>
			</comm-strategy>
			<comm-protocol name="CProtMpiSplited">
				<settings></settings>
			</comm-protocol></connection>
	</communications>
</layout-specification>
